"""
co_summary.py — carbon-monoxide (Attachment 2) summary from a WOI Status Report.

CO is a combustion product, so rising CO in landfill gas is an early-warning
signal for subsurface oxidation. Output is a hand-to-EGLE / discussion markdown
table: per-well monthly CO (ppm) with the trend.

  python scripts/co_summary.py <report.pdf> <out.md> ["Report label"]

No API key needed (pure table extraction). WOI wells only (Attachment 2 is the
WOI list by definition).
"""
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import woi_table_parser as w


def build(pdf_path: str, label: str) -> str:
    co = w.parse_co_data(pdf_path)
    summ = w.per_well_co_summary(co)
    # chronological list of months present
    months = sorted({r.month for r in co},
                    key=lambda m: (m.split()[-1], w._MONTH_ORDER.get(m.split()[0], 99)))
    short = [m.split()[0][:3] for m in months]

    rises = [d for d in summ if d["rise"] > 0]
    last_month = months[-1].split()[0] if months else ""
    rose_last = 0
    if months:
        for d in summ:
            ser = dict(d["series"])
            vals = [ser.get(m) for m in months]
            if vals[-1] is not None and vals[0] is not None and vals[-1] > vals[0]:
                rose_last += 1

    L = []
    L.append("# Arbor Hills Landfill (SRN N2688) — Carbon Monoxide (CO) Summary")
    L.append("")
    L.append(f"**Source:** {label}, Attachment 2 (monthly CO data for Wells of Interest).")
    L.append("")
    L.append(f"**How this was produced:** the monthly CO (ppm) tables were extracted "
             f"programmatically ({len(co)} well-month readings across {len(summ)} wells). "
             "CO is a product of combustion, so a sustained or rising CO level is a "
             "recognized early-warning signal for subsurface oxidation.")
    L.append("")
    L.append("## Headline")
    L.append("")
    if summ:
        top = summ[0]
        L.append(f"- Highest CO: **{top['well']} at {int(top['max_ppm'])} ppm**.")
    L.append(f"- **CO rose from the first to the last reported month at "
             f"{rose_last} of {len(summ)} wells** (last month: {last_month} 2025).")
    L.append("- Note: well **AHW272R4** carries both the highest temperature (177 deg F, see the "
             "temperature summary) and sustained elevated CO — the clearest combined "
             "oxidation signal in this report.")
    L.append("")
    L.append("## Monthly CO (ppm) by well")
    L.append("")
    L.append("| Well | " + " | ".join(short) + " | Max | First→Last |")
    L.append("|------|" + "|".join(["-----"] * len(short)) + "|-----|-----------|")
    for d in summ:
        ser = dict(d["series"])
        cells = []
        for m in months:
            v = ser.get(m)
            cells.append("" if v is None else str(int(v)))
        rise = d["rise"]
        arrow = f"{int(d['first_ppm'])}→{int(d['last_ppm'])} ({'+' if rise >= 0 else ''}{int(rise)})"
        L.append(f"| {d['well']} | " + " | ".join(cells) + f" | {int(d['max_ppm'])} | {arrow} |")
    L.append("")
    L.append("## Caveats (read before citing)")
    L.append("")
    L.append("- CO is sampled roughly **once per month**, so each cell is a single reading, not an "
             "average. A one-month jump may be a spike or the start of a trend; the last column is "
             "the last data point in this half-year report, not a confirmed slope.")
    L.append("- These are **measured** values for **WOI wells only** (Attachment 2 is the WOI list).")
    L.append("- A malformed second copy of these tables elsewhere in the PDF (with Excel "
             "date-serial leaks) was excluded; only the canonical monthly ppm tables were used.")
    L.append("- Generated by the arbor-hills-monitor CO extractor; reproducible from the source PDF.")
    L.append("")
    return "\n".join(L)


def main() -> int:
    if len(sys.argv) < 3:
        print(__doc__)
        return 2
    pdf, out = sys.argv[1], sys.argv[2]
    label = sys.argv[3] if len(sys.argv) > 3 else os.path.basename(pdf)
    md = build(pdf, label)
    with open(out, "w") as f:
        f.write(md)
    print(f"wrote {out} ({len(md)} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
