"""
woi_summary.py — generate a per-well elevated-temperature summary from a WOI
Status Report PDF. The output is a hand-to-EGLE markdown table.

  python scripts/woi_summary.py <report.pdf> <out.md> ["Report label"]

No API key needed — pure table extraction (woi_table_parser). Reproducible.
"""
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import woi_table_parser as w

EPA = 131   # EPA gas-well operating limit (deg F)
MACT = 145  # MACT limit (deg F)


def build(pdf_path: str, label: str) -> str:
    readings = w.parse_gas_extraction(pdf_path)
    valid = [r for r in readings if r.valid]
    woi = w.extract_woi_well_list(pdf_path)
    summ = w.per_well_summary(valid, woi_set=woi)

    n_wells = len({r.well_id for r in valid})
    hot = [d for d in summ if (d["max_temp_f"] or 0) >= EPA]
    n_woi_hot = sum(1 for d in hot if d["is_woi"])
    n_mact = sum(1 for d in summ if (d["max_temp_f"] or 0) >= MACT)
    n_woi_mact = sum(1 for d in summ if (d["max_temp_f"] or 0) >= MACT and d["is_woi"])

    def fnum(x, p=1):
        return "" if x is None else f"{x:.{p}f}"

    lines = []
    lines.append(f"# Arbor Hills Landfill (SRN N2688) — Elevated-Temperature Well Summary")
    lines.append("")
    lines.append(f"**Source:** {label}")
    lines.append("")
    lines.append("**How this was produced:** every per-well reading in the report's "
                 "gas-extraction tables (Attachment 1) was extracted programmatically and "
                 f"validated by the check that CH4 + CO2 + O2 + Balance sums to ~100% "
                 f"({len(valid)} of {len(readings)} readings passed, "
                 f"{100 * len(valid) // max(1, len(readings))}%). Values shown are "
                 "**as-found** readings (post-adjustment 'ADJ' rows excluded).")
    lines.append("")
    lines.append("**Thresholds:** 131 deg F = EPA gas-well operating limit; "
                 "145 deg F = MACT limit.")
    lines.append("")
    lines.append("**Scope note (important):** Attachment 1 is the full gas-extraction "
                 f"wellfield ({n_wells} wells), which is broader than the formally-"
                 f"designated Wells of Interest. The report's WOI list (Attachment 2) "
                 f"contains {len(woi)} wells. The 'On WOI list' column marks which of the "
                 "elevated wells are formally designated.")
    lines.append("")
    lines.append("## Headline")
    lines.append("")
    lines.append(f"- **{len(hot)} wells** reached at least 131 deg F "
                 f"(**{n_woi_hot}** of them on the formal WOI list).")
    lines.append(f"- **{n_mact} wells** reached at least the 145 deg F MACT limit "
                 f"(**{n_woi_mact}** of them on the formal WOI list).")
    if hot:
        top = hot[0]
        lines.append(f"- Hottest well: **{top['well']}** at "
                     f"**{fnum(top['max_temp_f'])} deg F** on {top['max_temp_date']} "
                     f"(O2 {fnum(top['o2_at_max_temp'])}%, CH4 {fnum(top['ch4_at_max_temp'])}% "
                     "at that reading). Elevated temperature with low methane and some "
                     "oxygen is consistent with subsurface oxidation.")
    lines.append("")
    lines.append("## Wells at or above 131 deg F (as-found)")
    lines.append("")
    lines.append("| Well | On WOI list | Max temp (F) | Date of max | O2 % at max | "
                 "CH4 % at max | >= 145 F MACT | Max O2 % (any reading) |")
    lines.append("|------|-------------|-------------|-------------|-------------|"
                 "-------------|---------------|------------------------|")
    for d in hot:
        lines.append(
            f"| {d['well']} | {'yes' if d['is_woi'] else 'no'} | "
            f"{fnum(d['max_temp_f'])} | {d['max_temp_date']} | "
            f"{fnum(d['o2_at_max_temp'])} | {fnum(d['ch4_at_max_temp'])} | "
            f"{'YES' if (d['max_temp_f'] or 0) >= MACT else ''} | "
            f"{fnum(d['max_o2_pct'])} |"
        )
    lines.append("")
    lines.append("## Caveats (read before citing)")
    lines.append("")
    lines.append("- **Denominator:** counts are over the full Attachment-1 wellfield, not "
                 "only the WOI. Use the 'On WOI list' column to speak precisely.")
    lines.append("- **O2 readings** elsewhere in the report reach ~20-24% at some probes, but "
                 "those are mostly near-surface / perimeter / sump points where near-"
                 "atmospheric oxygen is expected. The meaningful signal is oxygen **at a "
                 "well that is also hot** (oxygen feeding oxidation), shown in the O2-at-max "
                 "column above.")
    lines.append("- **Permitted vs measured:** the report's HOV-waiver *permitted ceilings* "
                 "(e.g. 155 and 180 deg F) are limits, not readings. Every number above is a "
                 "**measured** value.")
    lines.append("- Generated by the arbor-hills-monitor WOI extractor; reproducible from the "
                 "source PDF.")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) < 3:
        print(__doc__)
        return 2
    pdf, out = sys.argv[1], sys.argv[2]
    label = sys.argv[3] if len(sys.argv) > 3 else os.path.basename(pdf)
    md = build(pdf, label)
    with open(out, "w") as f:
        f.write(md)
    print(f"wrote {out} ({len(md)} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
